spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.21.38:3306/springcloud_sell?useUnicode=true&characterEncoding=utf-8
    jpa: show-sql:true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
#PRODUCT:
  #ribbon:
   # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule