spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://192.168.21.38:3306/springcloud_sell?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    jpa: show-sql:true
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
